//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_DK23TTC10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int id { get; set; }
        public Nullable<int> id_users { get; set; }
        public string email { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
}
